"""
Makes Gremlin behave the way you actually want to use it: it's the one
interface you talk to, it answers on its own whenever it can, and it
only reaches out to other registered models (local or API) when its
own answer looks uncertain. Whatever it learns from that consultation
gets written to a log so the exact same question doesn't need to
trigger a consult again.

Two things this file is careful about:

1. Other models are information sources during a consult, never the
   ones actually speaking to the user. The first-pass consult group
   (consult_models -- typically your local models) is asked, filtered
   down to whichever gave an actually confident answer (not just a
   successful API call -- an "I don't know" that came back with
   result.ok=True still doesn't count as help). If NOTHING in that
   first pass was confident, `last_resort_model` (if configured, e.g.
   Gemini) gets one dedicated final check -- not just another name in
   the same list. Whatever is found, the final synthesis is always
   generated by calling the persona itself (`gremlin`), so the voice
   and personality are always Gremlin's own -- the other models only
   ever supplied the raw material.

2. This deliberately does NOT auto-trigger a code edit. Consulting
   other models to answer a question is safe to automate -- worst case,
   you get a synthesized answer. Auto-editing Gremlin's own source
   based on whatever a user happened to type is a different risk
   entirely: it would mean any message, including an adversarial one,
   could cause the system to rewrite itself with no review step. So
   when a consult reveals an actual capability gap, this only ever
   *suggests* a goal string for the existing
   `python main.py improve ... --apply` flow -- a human still decides
   whether that patch is worth proposing and applying.
"""
from __future__ import annotations
import json
import os
import time
from typing import Optional

from .router import Router
from . import away_sync

UNCERTAINTY_MARKERS = [
    "i don't know", "i do not know", "i'm not sure", "i am not sure",
    "i don't have enough information", "i do not have enough information",
    "i cannot determine", "i can't determine", "unclear to me",
    "i'm unable to determine", "i am unable to determine",
    "i don't have access to", "i do not have access to",
    "not certain", "no information about this", "i have no way to know",
]

CONSULT_SYNTHESIS_PROMPT = (
    "You are answering a question using research gathered from other AI "
    "models, because your own first answer wasn't confident enough. Read "
    "the gathered answers below and give ONE clear, direct answer to the "
    "original question, in your own voice. Don't mention the consultation "
    "process or name which model said what -- just answer well, as yourself."
)


def seems_uncertain(text: str) -> bool:
    if not text or len(text.strip()) < 3:
        return True
    lowered = text.lower()
    return any(marker in lowered for marker in UNCERTAINTY_MARKERS)


def _log_path(root: str) -> str:
    path = os.path.join(root, "data", "learning_log.jsonl")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


def load_learned_answer(root: str, prompt: str) -> Optional[str]:
    """Exact-match lookup against past consultations. Intentionally
    simple -- no embeddings or fuzzy matching -- this is a starting
    point, not a full memory system."""
    path = _log_path(root)
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        for line in f:
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if entry.get("prompt") == prompt:
                return entry.get("final_answer")
    return None


def append_learning_log(root: str, entry: dict) -> None:
    entry["timestamp"] = time.time()
    with open(_log_path(root), "a") as f:
        f.write(json.dumps(entry) + "\n")


def _confident_results(results: dict) -> dict:
    """Only the ones that actually succeeded AND don't themselves read
    as uncertain -- a model that answered 'I'm not sure either' still
    counts as ok=True, but shouldn't be treated as a real contribution."""
    return {name: r for name, r in results.items() if r.ok and not seems_uncertain(r.text)}


def _recent_away_context(root: str, limit: int = 5) -> str:
    """This is the actual 'feed it back' piece: recent synced away-mode
    exchanges, handed to Gremlin as background so it can reference what
    was discussed while the user was out, rather than that history just
    sitting in a log file nobody reads. Deliberately small and bounded
    (last N entries) -- this is meant to be light context, not a full
    conversation-replay; it naturally ages out as new exchanges happen."""
    entries = away_sync.recent_entries(root, limit)
    if not entries:
        return ""
    lines = ["Recent conversation while the user was away from home (via phone, not this session):"]
    for e in entries:
        lines.append(f"- User asked: {e.get('prompt', '')}\n  You answered: {e.get('answer', '')}")
    return "\n".join(lines)


async def consult_and_learn(
    router: Router,
    persona_name: str,
    consult_models: list[str],
    prompt: str,
    root: str,
    last_resort_model: Optional[str] = None,
) -> dict:
    """
    1. Check if this exact question was already learned -- answer from
       memory with zero model calls if so.
    2. Otherwise ask the persona (gremlin) directly.
    3. If confident, done -- already in Gremlin's own voice, since it
       came straight from the persona backend.
    4. If uncertain, consult `consult_models` in parallel, keeping only
       answers that are themselves confident.
    5. If NONE of those were confident and `last_resort_model` is set,
       try that one specifically as a final check.
    6. Whatever confident material was found (from step 4 and/or 5),
       hand it to the persona itself to produce the final answer --
       so the voice is always Gremlin's, never a raw forward of
       whichever model happened to answer.
    """
    cached = load_learned_answer(root, prompt)
    if cached is not None:
        return {"answer": cached, "consulted": False, "from_memory": True, "contributors": []}

    context_note = _recent_away_context(root) or None

    primary_result = await router.route(persona_name, prompt, system=context_note)
    if not primary_result.ok:
        return {
            "answer": f"[error: {primary_result.error}]",
            "consulted": False,
            "from_memory": False,
            "contributors": [],
        }

    if not seems_uncertain(primary_result.text):
        return {
            "answer": primary_result.text,
            "consulted": False,
            "from_memory": False,
            "contributors": [],
        }

    # Uncertain -- first pass: the general consult group (typically local models)
    consult_results = await router.broadcast(consult_models, prompt) if consult_models else {}
    confident = _confident_results(consult_results)
    escalated = False

    # Nobody in the first pass actually knew -- try the dedicated last resort
    if not confident and last_resort_model:
        last_resort_result = await router.route(last_resort_model, prompt)
        last_resort_confident = _confident_results({last_resort_model: last_resort_result})
        if last_resort_confident:
            confident = last_resort_confident
            escalated = True

    if not confident:
        # Nobody could help, anywhere -- return the original uncertain
        # answer honestly rather than pretending consultation fixed anything.
        return {
            "answer": primary_result.text,
            "consulted": True,
            "from_memory": False,
            "contributors": [],
            "note": "consulted but nobody -- including the last-resort check -- had a confident answer",
        }

    # Hand the gathered material to Gremlin itself for the final answer,
    # so the voice is always its own, never a raw forward of another model.
    research_text = "\n\n".join(f"=== source ===\n{r.text}" for r in confident.values())
    synth_prompt = f"Original question: {prompt}\n\nGathered research:\n{research_text}"
    synth_system = f"{context_note}\n\n{CONSULT_SYNTHESIS_PROMPT}" if context_note else CONSULT_SYNTHESIS_PROMPT
    synthesis = await router.route(persona_name, synth_prompt, system=synth_system)
    final_answer = synthesis.text if synthesis.ok else next(iter(confident.values())).text

    append_learning_log(root, {
        "prompt": prompt,
        "primary_uncertain_answer": primary_result.text,
        "consulted_models": list(confident.keys()),
        "escalated_to_last_resort": escalated,
        "final_answer": final_answer,
    })

    return {
        "answer": final_answer,
        "consulted": True,
        "from_memory": False,
        "contributors": list(confident.keys()),
        "escalated": escalated,
    }
